server:
  port: 8080
spring:
  devtools:
    livereload:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://61.97.188.132:3306/realestate?useSSL=false
    username: root
    password: A8U?FDtbJe
  sql:
    init:
      mode: always
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION
logging:
  level:
    org.hibernate.SQL: debug

mybatis:
  type-aliases-package: kancho.realestate.comparingprices.domain.**
  mapper-locations: mybatis-mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
