DROP TABLE  IF EXISTS USER;

CREATE TABLE USER (
      USER_NO BIGINT NOT NULL auto_increment,
      ID VARCHAR(20) UNIQUE NOT NULL,
      PASSWORD VARCHAR(60) NOT NULL,
      JOIN_DTTM DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
      LAST_LOGIN_DTTM DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
      DELETE_DTTM DATETIME,
      PRIMARY KEY(`USER_NO`)
);